### ISSUE TITLE
How long will you support library? I love this 

### ISSUE THREAD

**Issue by LeetGod** [TheKimono/3Commas.Net#1]
I just tipped $50.

How long will you support this library? I find it really useful and would love to keep using it if you update it often, but I don't want to be left with an outdated library if they change a lot of the API, which they change every month or so.

**Comment by TheKimono** [comment]
I will keep supporting it as long as I use 3commas - which will probably be a long time :-) The source code will be here forever for anyone to take over if I abandon it at any point in the future.
