### ISSUE TITLE
Smart Trades Version 2

### ISSUE THREAD

**Issue by capricciobob** [TheKimono/3Commas.Net#24]
Apparently the Smart Trades in the current version call the v1 3Commas API. Those calls will be blank for any new Smart Trades. 

Need to use this instead.

https://github.com/3commas-io/3commas-official-api-docs/blob/master/smart_trades_v2_api.md#get-smart-trade-history-permission-smart_trade_read-security-signed

Is there a way to submit a suggestion? Thanks!

**Comment by MarcDrexler** [comment]
Hi @capricciobob 
Have you already started an implementation for Smart Trades v2?

**Comment by byrem6** [comment]
hi @MarcDrexler, 

Can you implement Smart Trade v2 ?

**Comment by psenka** [comment]
hi, i am waiting for this feature too, hope someone can fix it quickly. Thx

**Comment by hexate** [comment]
I have created a pull request with my initial (read incomplete) addition of SmartTrade V2 #39

**Comment by MarcDrexler** [comment]
@hexate Thanks a lot! We are also happy to accept incomplete implementations :) Every piece brings the library a step further.
