### ISSUE TITLE
Problem with fetching bots and serializing json

### ISSUE THREAD

**Issue by rodyla** [TheKimono/3Commas.Net#56]
When I try to fetch bots I get this error:

Could not serialize json to Bot[] : System.Exception: Value must be between 1 and 30   at XCommas.Net.Objects.RsiOptions.set_TimePeriod(Int32 value)

I think this line of code in XCommas.Net/XCommas.Net/Objects/BotStrategyOptions.cs is causing problems with some bots. I think old settings or not all bots have points causing this to happen.

if (value < 1 || value > 30) throw new Exception("Value must be between 1 and 30");

**Comment by MarcDrexler** [comment]
Recently 3Commas added new fields to the RSI options and I suspect this is a bot that doesn't have a valid value although it is mandatory. Could you verify this via the web interface and correct the missing value if necessary?

**Comment by rodyla** [comment]
I have about 30 people using my script and I was not able to parse any of the users bots. When I looked at all settings I noticed that some indicators like BB% have for example 0 as default value in the property points, also some other indicators like TradingView will have a higher value in the points property like 70. The validation would be alright for RSI but more indicators are using the points property.

**Comment by rodyla** [comment]
Ok I found out that a lot users have bots with RSI strategy and not having a Time Period set resulting in a parse error because the default value is set to 0. It would be nice when you fetch bots the serialisation does not fail. Maybe set the default Time Period to 7. So when it gets parsed and does not have a value it falls back to the default legacy RSI time period.

**Comment by MarcDrexler** [comment]
OK, I think I get it. I was not aware that the period is also used for other indicators.
Do you still think we should get rid of the validation?

Please have a look at #57

**Comment by rodyla** [comment]
I was wrong about the other indicators, took me a while to figuren it out. The problem is that older settings do not have the property Time Period (like 7 or 14). So during seralisation its automaticly sets to 0, since its an integer. Then the validation trows error because it must have a  value between 1 and 30. 

Problaby 2 options to fix this, maybe set the default value of the property of Time Period to 7. Because older bots with rsi had a value of 7. Or change the validation from 0 to 30.

**Comment by MarcDrexler** [comment]
No matter which option we choose, I somehow don't like either of them...
Nevertheless, i tend to go for the variant with a default, since the older bots had a value of 7, as you already write. That doesn't sound that much wrong.
Any other ideas or suggestions?
Otherwise I will go ahead and merge this PR.

**Comment by rodyla** [comment]
I also think thats the best way to go. Thanks!
