### ISSUE TITLE
Deal ID is now a long, not an int

### ISSUE THREAD

**Issue by UrmaGurd** [TheKimono/3Commas.Net#64]
Assume the 3commas API changed do that deal ID is now a long instead of an int. So responses from GetDeals fails with JSON deserialization error:
`Could not serialize json to Deal[] : Newtonsoft.Json.JsonReaderException: Could not convert to integer: 2150196129. Path '[0].id', line 1, position 17.`
Fix is pretty straightforward, change int to long in relevant places in:
- Deal.cs
- DealUpdateData.cs
- XCommasApi.cs

**Comment by UrmaGurd** [comment]
I have a local branch with the fix, but I don't have permissions to create pull requests.

**Comment by MarcDrexler** [comment]
Thank you @UrmaGurd 👍
