### ISSUE TITLE
Futures Bot issue

### ISSUE THREAD

**Issue by scipius** [TheKimono/3Commas.Net#8]
I get an error when I try to load a bot working on Futures (unable to serialize JSON).

I believe the issue comes from the fact that 3commas send a decimal as a leverage value but is define as INT in the code.

Example in JSON return 
 \"leverage_custom_value\":\"14.0\"

Definition of LeverageCustomValue 
public int? LeverageCustomValue { get; set; }

Could you look this up ?

**Comment by Grepsy** [comment]
Hey I got the same error:

```Error: An error occurred: 3Commas Connection Issue: Could not serialize json to Bot[] : Newtonsoft.Json.JsonReaderException: Could not convert string to integer: 2.0. Path '[0].leverage_custom_value', line 1, position 1279.```

I'll try and create a PR.

**Comment by MarcDrexler** [comment]
I've tested it and it works 👍 

@TheKimono you can close this one.

**Comment by scipius** [comment]
Awesome, thanks!

**Comment by TheKimono** [comment]
Thanks @MarcDrexler 👍
